"""initial schema

Revision ID: be9bd71bf67c
Revises:
Create Date: 2026-07-03 14:51:33.974795

Creates the list-management slice of TDD §5.1 (users, restaurants, lists,
list_items, visits, taste_profiles, recommendation_logs). This is DB-agnostic
and applies to both dev SQLite and Postgres:

  * `embedding` / JSON columns are stored as JSON here — NOT pgvector. Fixing the
    vector dimension N and switching to a pgvector column is a deliberate FOLLOW-UP
    migration, blocked on choosing the embedding model (TDD §9).
  * geo retrieval uses the derived latitude/longitude B-tree indexes. The Postgres
    `geography(Point)` + GIST radius index and the GIN cuisine index (TDD §5.2) are
    likewise a later Postgres-only migration.

So this establishes the migration framework without being gated on those open
decisions; the specialization lands as additional revisions on top.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9bd71bf67c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('categories_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_restaurant_source')
    )
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurants_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurants_longitude'), ['longitude'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lists_user_id'), ['user_id'], unique=False)

    op.create_table('recommendation_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('candidate_set', sa.JSON(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('llm_response', sa.JSON(), nullable=True),
    sa.Column('shown_restaurant_ids', sa.JSON(), nullable=True),
    sa.Column('user_feedback', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_logs_user_id'), ['user_id'], unique=False)

    op.create_table('taste_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('cuisines_preferred', sa.JSON(), nullable=True),
    sa.Column('price_pref', sa.JSON(), nullable=True),
    sa.Column('dietary_restrictions', sa.JSON(), nullable=True),
    sa.Column('ambiance_prefs', sa.JSON(), nullable=True),
    sa.Column('derived_summary', sa.Text(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taste_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taste_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('visits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=False),
    sa.Column('visited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_restaurant_id'), ['restaurant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_user_id'), ['user_id'], unique=False)

    op.create_table('list_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('list_id', sa.String(), nullable=False),
    sa.Column('restaurant_id', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'restaurant_id', name='uq_listitem')
    )
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_items_list_id'), ['list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_list_items_restaurant_id'), ['restaurant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_list_items_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_list_items_list_id'))

    op.drop_table('list_items')
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_user_id'))
        batch_op.drop_index(batch_op.f('ix_visits_restaurant_id'))

    op.drop_table('visits')
    with op.batch_alter_table('taste_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taste_profiles_user_id'))

    op.drop_table('taste_profiles')
    with op.batch_alter_table('recommendation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_logs_user_id'))

    op.drop_table('recommendation_logs')
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lists_user_id'))

    op.drop_table('lists')
    op.drop_table('users')
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurants_longitude'))
        batch_op.drop_index(batch_op.f('ix_restaurants_latitude'))

    op.drop_table('restaurants')
    # ### end Alembic commands ###
